version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
     
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source PYTHON dependencies.
      - apt-get install python3.10
      - pip install django
#  post_build:
 #   commands:
 #3     - echo Build started on `date`
 #     - python3 manage.py runserver --noreload
