version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
     
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source PYTHON dependencies.
      - apt-get install python3.10
      - aptinstall python3-pip
      - pip install django
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - python manage.py runserver
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
